In [1]:
import numpy as np

In [2]:
sales = [0,5,155,0,518,0,1827,616,317,325]

In [3]:
# sales python list or tuples
sales

[0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [4]:
sales_array = np.array(sales)

In [5]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

# array properties
- ndim
- shape
- size
- dtype
  #properties of the array

In [6]:
type(sales_array)

numpy.ndarray

In [7]:
print(f"ndim : {sales_array.ndim}")
print(f"shape : {sales_array.shape}")
print(f"size : {sales_array.size}")
print(f"dtype : {sales_array.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64


# 2 D Array

In [8]:
# has to be of same length
sales = [[0,5,155,0,518], [0,1827,616,317,325]]

In [9]:
sales_2dArray = np.array(sales)

In [10]:
sales_2dArray

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [11]:
print(f"ndim : {sales_2dArray.ndim}")
print(f"shape : {sales_2dArray.shape}")
print(f"size : {sales_2dArray.size}")
print(f"dtype : {sales_2dArray.dtype}")

ndim : 2
shape : (2, 5)
size : 10
dtype : int64


In [12]:
array = np.array(range(5))

In [13]:
array

array([0, 1, 2, 3, 4])

In [14]:
array_2d = np.array([range(5),range(5)])

In [16]:
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [18]:
array_2d.T.ndim

2

In [19]:
array_2d.ndim

2

In [20]:
array_2d.dtype

dtype('int64')

In [21]:
np.array(['I','love','pandas'])

array(['I', 'love', 'pandas'], dtype='<U6')

# Exercise 1

In [22]:
# convert below list into array and observe it's properties
my_list = [ x*10 for x in range(1,11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
print(f"ndim : {my_array.ndim}")
print(f"shape : {my_array.shape}")
print(f"size : {my_array.size}")
print(f"dtype : {my_array.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64


In [24]:
my_array.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [25]:
my_array.reshape(2,5).ndim

2

# Create arrays 
- ones
- zeros
- arrange
- linshape
- reshape

In [26]:
# np.ones((rows,cols),dtype)
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones(15).reshape(15,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [28]:
np.ones(2,dtype='int')

array([1, 1])

In [29]:
# np.zeros((rows,cols),dtype))
np.zeros(100,'int').reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.zeros((5,20),'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
np.zeros((5,20),'int').T

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
#np.arange(start,stop,step) -- start is 0 and step is 1 by default {stop is not inclusive } s
# same as range in base python
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
# linspace create an array for equal space 
# helpful in chart indexes 
# stop is inclusive 
# np.linspace(start, stop, n)

In [37]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [38]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [39]:
np.linspace(8, 64 , 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [40]:
np.linspace(0, 64 , 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [41]:
# reshape
# generate an error if shape is not compatible 

# random number arrays
-default_rng - seed is reproducible np.defalut_rng(seed)
- random methos uniform distribution bet 0 and 1 rng.random(n)
- normal (distribution) returns n random numbers from a normal distribution with a given mean and standard deviation rng.normal(mean, stdev,n)
- (rng) is the standard variable name for the default_rng number generator

In [42]:
from numpy.random import default_rng

rng = default_rng(12345)

random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [43]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [44]:
rng.integers(0,10,100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5])

In [45]:
rng.normal(50,5,10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

In [46]:
rng = default_rng(12345)
mean , stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

# Exercise 2

In [47]:
np_array = np.linspace(10,100,10).reshape(5,2)
np_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [48]:
np_array = np.arange(10,101,10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [49]:
np_array = (np.arange(1,11)*10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [50]:
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [51]:
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random([3,3])
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# indexing and slicing 
- array[index] (0-indexed)
- array[start:stop:step size]

In [52]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs','snacks','beverages','coffee','tea','spices'])

In [53]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [54]:
print(product_array[1])

vegetables


In [55]:
print(product_array[-1])

spices


In [56]:
print(product_array[:5])

['fruits' 'vegetables' 'cereal' 'dairy' 'eggs']


In [57]:
print(product_array[5::2])

['snacks' 'coffee' 'spices']


# indexing and slicing 2d array
- array[row index, column index]
- array[start:stop:step size, start:stop:step size]

In [58]:
product_array2D = product_array.reshape(2,5)
product_array2D

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [59]:
product_array2D[1,2]

np.str_('coffee')

In [60]:
product_array2D[:, 2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

In [61]:
product_array2D[1:,:]

array([['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [62]:
#integer 
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
integer_array[2]

np.int64(2)

In [64]:
integer_array[-2]

np.int64(10)

In [65]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [66]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [67]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [69]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
# entire array 
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
# exclude top array 
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
# last colummn 
new_array[:,3]

array([ 3,  7, 11])

In [73]:
# only exclude 1st column 
new_array[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [74]:
# grid value from array 
new_array[2,1]

np.int64(9)

# Excercise 3 
random_array

In [75]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [76]:
# first 2 rows 
random_array[:2,:]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [77]:
# first column 
random_array[:,:1]

array([[0.24742606],
       [0.06066207],
       [0.1108689 ]])

In [78]:
random_array[:,0] # transpose as a row 

array([0.24742606, 0.06066207, 0.1108689 ])

In [79]:
#second number in third row 
random_array[2,1]

np.float64(0.04305584439252108)

### Array operation 
- vectorization and broadcasting , element the looping although happening in c and not in base phython

In [80]:
sales = [[0,5, 155, 0 , 518],[0,1827,616,317,325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [81]:
sales_array + 2 # adds to every element in the array

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  618,  319,  327]])

In [82]:
quantity = sales_array[0, :]
price = sales_array[1, :]

quantity * price # multiple element vice 

array([     0,   9135,  95480,      0, 168350])

In [83]:
rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [84]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [85]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [86]:
(inventory / 2).dtype

dtype('float64')

In [87]:
price = (rng.random(11) + 10).round(2)

price

array([10.09, 10.88, 10.73, 10.73, 10.56, 10.34, 10.06, 10.36, 10.2 ,
       10.43, 10.1 ])

In [88]:
price * inventory

ValueError: operands could not be broadcast together with shapes (11,) (10,) 

In [89]:
price = (rng.random(10) + 10).round(2)

price

array([10.52, 10.8 , 10.08, 10.15, 10.9 , 10.66, 10.73, 10.77, 10.03,
       10.78])

In [90]:
price * inventory

array([410.28, 421.2 , 937.44, 872.9 , 523.2 , 490.36, 515.04, 323.1 ,
       110.33, 614.46])

In [91]:
(price * inventory).sum()

np.float64(5218.31)

In [92]:
inventory_list = list(inventory)

inventory_list

[np.int64(39),
 np.int64(39),
 np.int64(93),
 np.int64(86),
 np.int64(48),
 np.int64(46),
 np.int64(48),
 np.int64(30),
 np.int64(11),
 np.int64(57)]

In [93]:
inventory_list + 2

TypeError: can only concatenate list (not "int") to list

In [94]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)

new_inventory

[np.int64(41),
 np.int64(41),
 np.int64(95),
 np.int64(88),
 np.int64(50),
 np.int64(48),
 np.int64(50),
 np.int64(32),
 np.int64(13),
 np.int64(59)]

In [95]:
 [x + 2 for x in inventory_list]

[np.int64(41),
 np.int64(41),
 np.int64(95),
 np.int64(88),
 np.int64(50),
 np.int64(48),
 np.int64(50),
 np.int64(32),
 np.int64(13),
 np.int64(59)]

In [96]:
[x * y for x , y in zip(inventory_list , price)]

[np.float64(410.28),
 np.float64(421.20000000000005),
 np.float64(937.44),
 np.float64(872.9),
 np.float64(523.2),
 np.float64(490.36),
 np.float64(515.04),
 np.float64(323.09999999999997),
 np.float64(110.33),
 np.float64(614.4599999999999)]

### Exercise 4

In [97]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [98]:
# grap 1st 6 elements of random array 
#discount_pct = random_array.flatten()[:6]
discount_pct = random_array[:2,:].reshape(6)
discount_pct


array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [99]:
# subtract 1 from discount_pct to get pct_owed

pct_owed = 1 - discount_pct 

pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [100]:
final_owed = (total * pct_owed).round(2)

final_owed

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

### filter arrays 

In [101]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [102]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

In [103]:
sales_array[ sales_array != 0]

array([   5,  155,  518, 1827,  616,  317,  325])

In [104]:
# multiple logical tests
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [105]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [106]:
mask = (sales_array > 100) & (sales_array < 500)

In [107]:
sales_array[mask]

array([155, 317, 325])

In [114]:
# filter arrays based on values in other arrays
sales_array = np.array([  0,   5, 155,   0, 518])

In [115]:
sales_array

array([  0,   5, 155,   0, 518])

In [116]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [118]:
product_array[0:5][sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

In [119]:
# modify array values
sales_array

array([  0,   5, 155,   0, 518])

In [120]:
sales_array[1] = 25

sales_array

array([  0,  25, 155,   0, 518])

In [121]:
sales_array[ sales_array == 0] = 5

sales_array

array([  5,  25, 155,   5, 518])

In [123]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [124]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [125]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
# with test 
even_odd = np.array(['even', 'odd'] * 10)

even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [127]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [128]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [129]:
my_array[even_odd != 'odd'] = 0

my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [130]:
my_array[2] = 2

my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [132]:
mask = (even_odd != 'odd') | (even_odd != 'even')

In [133]:
even_odd[mask] # all returned coz of or |

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [134]:
mask = (even_odd != 'odd') & (even_odd != 'even')

In [135]:
even_odd[mask] # none returned coz of and &

array([], dtype='<U4')

### where 
np.where(logical test,
         value if True,
         value if False)

In [139]:
inventory_array = np.array([12, 102, 18, 0, 0])

inventory_array

array([ 12, 102,  18,   0,   0])

In [140]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [141]:
np.where(inventory_array <= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [143]:
np.where(inventory_array <= 0, "Out of Stock", product_array[0:5])

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [144]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
np.where(my_array % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [146]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9, my_array, 'odd')) # chain another where 

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

### Exercise 5

In [147]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [148]:
products = np.array(
    ['salad', 'bread', 'mustard', 'rare tomato', 'cola', 'gourment ice cream'])

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourment ice cream'], dtype='<U18')

In [149]:
# 1 price greater than 25 
p_gt_25 = products[prices > 25]
p_gt_25

array(['rare tomato', 'gourment ice cream'], dtype='<U18')

In [153]:
mask = (prices > 25) | (products == 'cola')

In [155]:
# 2 include cola
fancy_feast_special = products[mask]

fancy_feast_special

array(['rare tomato', 'cola', 'gourment ice cream'], dtype='<U18')

In [156]:
# 3 create shipping cost 
shipping_cost = np.where(prices > 20 , 0 , 5)
shipping_cost

array([5, 5, 0, 0, 5, 0])

### array aggregation 

In [157]:
sales = [[0,5, 155, 0 , 518],[0,1827,616,317,325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [158]:
sales_array.sum()

np.int64(3763)

In [159]:
sales_array.max()

np.int64(1827)

In [160]:
sales_array.min()

np.int64(0)

In [161]:
sales_array.mean()

np.float64(376.3)

In [162]:
# aggregate across rows 
sales_array.sum(axis = 0)

array([   0, 1832,  771,  317,  843])

In [163]:
# aggregate across columns 
sales_array.sum(axis = 1)

array([ 678, 3085])

In [177]:
rng = np.random.default_rng(616)

In [178]:
price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [179]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43])

In [180]:
inventory.mean()

np.float64(35.3)

In [181]:
inventory.sum()

np.int64(353)

In [182]:
inventory.max()

np.int64(80)

In [183]:
inventory.min()

np.int64(6)

In [184]:
inventory.std()

np.float64(20.48438429633656)

In [186]:
(price * inventory)

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [187]:
(price * inventory).sum()

np.float64(1848.2900000000002)

In [188]:
(price * inventory).min()

np.float64(18.36)

In [189]:
(price * inventory).argmin()

np.int64(3)

In [190]:
(price * inventory).argmax()

np.int64(0)

In [191]:
price_2d = price.reshape(5,2)

price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [193]:
price_2d.sum(axis=0)

array([30.45, 25.55])

In [194]:
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [195]:
price_2d.mean(axis=0)

array([6.09, 5.11])

### Array functions

In [196]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [198]:
np.median(sales_array)

np.float64(236.0)

In [199]:
np.mean(sales_array)

np.float64(376.3)

In [200]:
np.percentile(sales_array, 90)

np.float64(737.0999999999996)

In [201]:
np.percentile(sales_array, 50)

np.float64(236.0)

In [202]:
np.unique(sales_array)

array([   0,    5,  155,  317,  325,  518,  616, 1827])

In [203]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 0.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [204]:
price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

inventory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])

product_value = price * inventory

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [207]:
product_value.sort()

product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [205]:
reshaped_product_value = product_value.reshape(2,5)

reshaped_product_value

array([[205.4 , 158.4 , 138.4 , 186.24,   6.24],
       [202.92, 106.44,   3.68,  26.15, 403.2 ]])

In [208]:
np.median(reshaped_product_value)

np.float64(148.4)

In [209]:
np.percentile(reshaped_product_value, 90)

np.float64(225.17999999999992)

In [210]:
np.percentile(reshaped_product_value, 10)

np.float64(5.984)

In [211]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [212]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [213]:
np.unique(np.ones(100))

array([1.])

### sorting array

In [226]:
sales = [[0,5, 155, 0 , 518],[0,1827,616,317,325]]

sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [224]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [222]:
sales_array.sort() # default is by axis 1 2d by row 

sales_array

array([[   0,    0,    5,  155,  518],
       [   0,  317,  325,  616, 1827]])

In [225]:
sales_array.sort(axis = 0) # axis = 0 will sort by columns 
sales_array

array([[   0,    5,  155,    0,  325],
       [   0, 1827,  616,  317,  518]])

In [227]:
price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])

inventory = np.array([79, 22, 20, 48, 8, 76, 12, 16, 5, 64])

product_value = price * inventory

product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [228]:
np.sort(product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [229]:
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [230]:
product_value.sort()

In [231]:
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [232]:
product_value[0]

np.float64(3.68)

In [233]:
product_value[-1]

np.float64(403.2)

In [234]:
product_value[::-1] # negative step size reverse 

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])

### Exercise 6

In [236]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [238]:
# grap first top 3 highest priced items in our list 
prices.sort()
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [243]:
top_3 = prices[3:]
top_3

array([22.49, 49.99, 99.99])

In [251]:
top_3 = prices[-3:]
top_3

array([22.49, 49.99, 99.99])

In [244]:
top_3.mean()

np.float64(57.49)

In [246]:
np.median(top_3)

np.float64(49.99)

In [247]:
top_3.max()

np.float64(99.99)

In [248]:
top_3.min()

np.float64(22.49)

In [254]:
print(f"Mean: {top_3.mean()}")
print(f"Max: {top_3.max()}")
print(f"Min: {top_3.min()}")
print(f"Median: {np.median(top_3)}")

Mean: 57.49
Max: 99.99
Min: 22.49
Median: 49.99


In [249]:
# calculate the number of unique price tiers in price_tiers
price_tiers =np.array(['budget','budget','mid-tier','luxury','mid-tier','luxury'])
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

### Vectorization - is the process of pushing array operations into optimized C code, which is easier and more efficient 
than writing for loops

In [261]:
def for_loop_multiply_lists(list1, list2):
    product_list = []
    for element1, element2 in zip(list1, list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 + array2
    

In [266]:
list1 = list(range(100000))
list2 = list(range(100000))

In [267]:
%%timeit -r 5 -n 10000
for_loop_multiply_lists(list1, list2)

3.3 ms ± 50.8 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [268]:
array1 = np.array(list1)
array2 = np.array(list2)

In [269]:
%%timeit -r 5 -n 10000
multiply_arrays(list1, list2)

297 µs ± 5.8 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


### Broadcasting lets you perform vectorized operations with arrays of sizes, where numpy will expand the smaller array
to fit the larger one 
- Single values (scalars) can be broadcast into arrays of any dimension
- Dimensions with a length greater than one must be the same size
- Compatible shapes

In [270]:
test_array = np.array([[1,2,3],[1,2,3],[1,2,3]])

test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [271]:
test_array + 1

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [272]:
test_array + np.array([3, 2, 1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [273]:
test_array + np.array([3,2,1]).reshape(3,1)

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [274]:
test_array + np.array([2,1]) # error out 

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [275]:
test_array[0, :]

array([1, 2, 3])

In [278]:
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [277]:
test_array[:, 1].reshape(3,1)

array([[2],
       [2],
       [2]])

In [279]:
test_array[0, :] + test_array[:, 1].reshape(3,1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [280]:
np.ones((2,3,3), dtype=int) + np.ones(3, dtype=int)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [281]:
np.ones((2,3,3), dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [282]:
np.ones(3, dtype=int)

array([1, 1, 1])

### Exercise 7

In [285]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "./retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)


In [286]:
retail_df.head()

id        date  store_nbr        family    sales  onpromotion
0  1956943  2016-01-07         18          EGGS   177.00            0
1  1956944  2016-01-07         18  FROZEN FOODS    36.00            0
2  1956945  2016-01-07         18     GROCERY I  2291.06            6
3  1956946  2016-01-07         18    GROCERY II    16.00            0
4  1956947  2016-01-07         18      HARDWARE     2.00            0

In [290]:
family_array = np.array(retail_df["family"])

sales_array = np.array(retail_df["sales"])


In [302]:
# filter only sales with produce family
produce_sales = np.array(retail_df.loc[family_array == 'PRODUCE', 'sales'])
produce_sales

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [322]:
produce_array = sales_array[family_array == "PRODUCE"]
produce_array

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [304]:
produce_sales.size

30

In [305]:
produce_sales.shape

(30,)

In [323]:
rng = np.random.default_rng(2022)
random_aaray = rng.random(30)

produce_sales[produce_sales_half < .5]

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [319]:
produce_sales_half.mean()

np.float64(0.4564172663933915)

In [320]:
np.median(produce_sales_half)

np.float64(0.3218479857068822)