In [1]:
import numpy as np

In [2]:
sales = [0,5,155,0,518,0,1827,616,317,325]

In [3]:
# sales python list or tuples
sales

[0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

In [4]:
sales_array = np.array(sales)

In [5]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

# array properties
- ndim
- shape
- size
- dtype
  #properties of the array

In [6]:
type(sales_array)

numpy.ndarray

In [9]:
print(f"ndim : {sales_array.ndim}")
print(f"shape : {sales_array.shape}")
print(f"size : {sales_array.size}")
print(f"dtype : {sales_array.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64


# 2 D Array

In [10]:
# has to be of same length
sales = [[0,5,155,0,518], [0,1827,616,317,325]]

In [11]:
sales_2dArray = np.array(sales)

In [12]:
sales_2dArray

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [13]:
print(f"ndim : {sales_2dArray.ndim}")
print(f"shape : {sales_2dArray.shape}")
print(f"size : {sales_2dArray.size}")
print(f"dtype : {sales_2dArray.dtype}")

ndim : 2
shape : (2, 5)
size : 10
dtype : int64


In [14]:
array = np.array(range(5))

In [15]:
array

array([0, 1, 2, 3, 4])

In [20]:
array_2d = np.array([range(5),range(5)])

In [22]:
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [24]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [25]:
array_2d.T.ndim

2

In [27]:
array_2d.ndim

2

In [28]:
array_2d.dtype

dtype('int64')

In [29]:
np.array(['I','love','pandas'])

array(['I', 'love', 'pandas'], dtype='<U6')

# Exercise 1

In [34]:
# convert below list into array and observe it's properties
my_list = [ x*10 for x in range(1,11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
print(f"ndim : {my_array.ndim}")
print(f"shape : {my_array.shape}")
print(f"size : {my_array.size}")
print(f"dtype : {my_array.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64


In [36]:
my_array.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [37]:
my_array.reshape(2,5).ndim

2

# Create arrays 
- ones
- zeros
- arrange
- linshape
- reshape

In [41]:
# np.ones((rows,cols),dtype)
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.ones(15).reshape(15,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [44]:
np.ones(2,dtype='int')

array([1, 1])

In [45]:
# np.zeros((rows,cols),dtype))
np.zeros(100,'int').reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
np.zeros((5,20),'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
np.zeros((5,20),'int').T

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [50]:
#np.arange(start,stop,step) -- start is 0 and step is 1 by default {stop is not inclusive } s
# same as range in base python
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [53]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# linspace create an array for equal space 
# helpful in chart indexes 
# stop is inclusive 
# np.linspace(start, stop, n)

In [58]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [59]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [60]:
np.linspace(8, 64 , 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [61]:
np.linspace(0, 64 , 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [ ]:
# reshape
# generate an error if shape is not compatible 

# random number arrays
-default_rng - seed is reproducible np.defalut_rng(seed)
- random methos uniform distribution bet 0 and 1 rng.random(n)
- normal (distribution) returns n random numbers from a normal distribution with a given mean and standard deviation rng.normal(mean, stdev,n)
- (rng) is the standard variable name for the default_rng number generator

In [66]:
from numpy.random import default_rng

rng = default_rng(12345)

random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [63]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [64]:
rng.integers(0,10,100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5])

In [65]:
rng.normal(50,5,10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

In [68]:
rng = default_rng(12345)
mean , stddev = 5, 1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

# Exercise 2

In [74]:
np_array = np.linspace(10,100,10).reshape(5,2)
np_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [85]:
np_array = np.arange(10,101,10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [88]:
np_array = (np.arange(1,11)*10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [89]:
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [91]:
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random([3,3])
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# indexing and slicing 
- array[index] (0-indexed)
- array[start:stop:step size]

In [92]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs','snacks','beverages','coffee','tea','spices'])

In [93]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [94]:
print(product_array[1])

vegetables


In [95]:
print(product_array[-1])

spices


In [96]:
print(product_array[:5])

['fruits' 'vegetables' 'cereal' 'dairy' 'eggs']


In [99]:
print(product_array[5::2])

['snacks' 'coffee' 'spices']


# indexing and slicing 2d array
- array[row index, column index]
- array[start:stop:step size, start:stop:step size]

In [101]:
product_array2D = product_array.reshape(2,5)
product_array2D

array([['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [104]:
product_array2D[1,2]

np.str_('coffee')

In [105]:
product_array2D[:, 2:]

array([['cereal', 'dairy', 'eggs'],
       ['coffee', 'tea', 'spices']], dtype='<U10')

In [106]:
product_array2D[1:,:]

array([['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')